// <auto-generated/>
#nullable enable

namespace TestApp;

partial class HighPrioritySystem : global::GFramework.Core.Abstractions.Bases.IPrioritized
{
    /// <summary>
    /// 获取优先级值: -50
    /// </summary>
    public int Priority => -50;
}