// <auto-generated />
using GFramework.Core.Abstractions.Logging;
using GFramework.Core.Logging;

namespace TestApp;

partial class MyService
{
    /// <summary>Auto-generated logger</summary>
    private static readonly ILogger MyLogger = LoggerFactoryResolver.Provider.CreateLogger("MyService");
}
