using GFramework.Godot.SourceGenerators.Registration;
using GFramework.Godot.SourceGenerators.Tests.Core;

namespace GFramework.Godot.SourceGenerators.Tests.Registration;

[TestFixture]
public class AutoRegisterExportedCollectionsGeneratorTests
{
    [Test]
    public async Task Generates_Batch_Registration_Method_For_Annotated_Collections()
    {
        const string source = """
                              #nullable enable
                              using System;
                              using System.Collections.Generic;
                              using GFramework.Godot.SourceGenerators.Abstractions;

                              namespace GFramework.Godot.SourceGenerators.Abstractions
                              {
                                  [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                  public sealed class AutoRegisterExportedCollectionsAttribute : Attribute { }

                                  [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                                  public sealed class RegisterExportedCollectionAttribute : Attribute
                                  {
                                      public RegisterExportedCollectionAttribute(string registryMemberName, string registerMethodName) { }
                                  }
                              }

                              namespace TestApp
                              {
                                  public sealed class IntRegistry
                                  {
                                      public void Register(int value) { }
                                  }

                                  [AutoRegisterExportedCollections]
                                  public partial class Bootstrapper<TReference, TNotNull, TValue, TUnmanaged>
                                      where TReference : class?
                                      where TNotNull : notnull
                                      where TValue : struct
                                      where TUnmanaged : unmanaged
                                  {
                                      private readonly IntRegistry? _registry = new();

                                      [RegisterExportedCollection(nameof(_registry), nameof(IntRegistry.Register))]
                                      public List<int>? Values { get; } = new();
                                  }
                              }
                              """;

        const string expected = """
                                // <auto-generated />
                                #nullable enable

                                namespace TestApp;

                                partial class Bootstrapper<TReference, TNotNull, TValue, TUnmanaged>
                                    where TReference : class?
                                    where TNotNull : notnull
                                    where TValue : struct
                                    where TUnmanaged : unmanaged
                                {
                                    private void __RegisterExportedCollections_Generated()
                                    {
                                        if (this.Values is not null && this._registry is not null)
                                        {
                                            foreach (var __generatedItem in this.Values)
                                            {
                                                this._registry.Register(__generatedItem);
                                            }
                                        }
                                    }
                                }

                                """;

        await GeneratorTest<AutoRegisterExportedCollectionsGenerator>.RunAsync(
            source,
            ("TestApp_Bootstrapper.AutoRegisterExportedCollections.g.cs", expected));
    }

    [Test]
    public async Task Reports_Diagnostic_When_Collection_Element_Type_Cannot_Be_Inferred()
    {
        const string source = """
                              using System;
                              using System.Collections;
                              using GFramework.Godot.SourceGenerators.Abstractions;

                              namespace GFramework.Godot.SourceGenerators.Abstractions
                              {
                                  [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                  public sealed class AutoRegisterExportedCollectionsAttribute : Attribute { }

                                  [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                                  public sealed class RegisterExportedCollectionAttribute : Attribute
                                  {
                                      public RegisterExportedCollectionAttribute(string registryMemberName, string registerMethodName) { }
                                  }
                              }

                              namespace TestApp
                              {
                                  public sealed class IntRegistry
                                  {
                                      public void Register(int value) { }
                                  }

                                  [AutoRegisterExportedCollections]
                                  public partial class Bootstrapper
                                  {
                                      private readonly IntRegistry _registry = new();

                                      [RegisterExportedCollection(nameof(_registry), nameof(IntRegistry.Register))]
                                      public IEnumerable {|#0:Values|} { get; } = new ArrayList();
                                  }
                              }
                              """;

        var test = new CSharpSourceGeneratorTest<AutoRegisterExportedCollectionsGenerator, DefaultVerifier>
        {
            TestState =
            {
                Sources = { source }
            },
            DisabledDiagnostics = { "GF_Common_Trace_001" }
        };

        test.ExpectedDiagnostics.Add(new DiagnosticResult("GF_AutoExport_005", DiagnosticSeverity.Error)
            .WithLocation(0)
            .WithArguments("Values"));

        await test.RunAsync();
    }

    [Test]
    public async Task Generates_Batch_Registration_Method_When_Register_Method_Uses_Array_Parameter()
    {
        const string source = """
                              #nullable enable
                              using System;
                              using System.Collections.Generic;
                              using GFramework.Godot.SourceGenerators.Abstractions;

                              namespace GFramework.Godot.SourceGenerators.Abstractions
                              {
                                  [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                                  public sealed class AutoRegisterExportedCollectionsAttribute : Attribute { }

                                  [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                                  public sealed class RegisterExportedCollectionAttribute : Attribute
                                  {
                                      public RegisterExportedCollectionAttribute(string registryMemberName, string registerMethodName) { }
                                  }
                              }

                              namespace TestApp
                              {
                                  public sealed class ArrayRegistry
                                  {
                                      public void Register(int[] value) { }
                                  }

                                  [AutoRegisterExportedCollections]
                                  public partial class Bootstrapper
                                  {
                                      private readonly ArrayRegistry _registry = new();

                                      [RegisterExportedCollection(nameof(_registry), nameof(ArrayRegistry.Register))]
                                      public List<int[]> Values { get; } = new();
                                  }
                              }
                              """;

        const string expected = """
                                // <auto-generated />
                                #nullable enable

                                namespace TestApp;

                                partial class Bootstrapper
                                {
                                    private void __RegisterExportedCollections_Generated()
                                    {
                                        if (this.Values is not null && this._registry is not null)
                                        {
                                            foreach (var __generatedItem in this.Values)
                                            {
                                                this._registry.Register(__generatedItem);
                                            }
                                        }
                                    }
                                }

                                """;

        await GeneratorTest<AutoRegisterExportedCollectionsGenerator>.RunAsync(
            source,
            ("TestApp_Bootstrapper.AutoRegisterExportedCollections.g.cs", expected));
    }
}
